apiVersion: v1
kind: ConfigMap
metadata:
  name: openbreak-config
  namespace: openbreak
  labels:
    app.kubernetes.io/name: openbreak
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_NAME: "OpenBreak"
  AUTH_URL: "https://openbreak.pro"
  NEXTAUTH_URL: "https://openbreak.pro"
