apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbreak-postgres-data
  namespace: openbreak
  labels:
    app.kubernetes.io/name: openbreak
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
